---
- hosts: all
  #gather_facts: yes
  #remote_user: ansible
  roles:
    - role: dispatch
      vars:
        linux_config_dispatcher_roles:
          - {role: os_mgmt.linux_config.motd, var: linux_config_motd, tags: motd}
